url: "https://www.everimus.com"
baseurl: ""

#baseurl: "/"
# If you are building a GitHub project page then use these settings:
# url: "https://www.iamgini.com/site2/"
# baseurl: "/site2"

# Site settings
title: everimus
email: devops@everimus.com
description: "opensource and smart"
metadescription : "Looking holistically at clients’ business needs, everimus can help businesses better leverage the benefits of Automation, Containerization, DevOps and fine tune cloud solutions. everimus's range of technology services include, but not limited to: Cloud Management, Enterprise Automation, DevOps & Containerization."
tagline: "opensource and smart"
titletagline: "Enterprise Solutions for Automation, Containerization and DevOps"
metaimage: "assets/images/everimus-meta-image.png"

favicon: 'assets/images/favicon.ico'

# Team names, titles and social links
people:
#- name: Kay Garland
#  pic: 1
#  position: Lead Designer
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: stack-overflow
#      url: #

# ---------------------------------------------------
- name: devops
  pic: devops
  position: DevOps Team
  social:
    - title: facebook
      url: https://www.facebook.com/everimus


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  #- title: facebook
  #  url: https://www.facebook.com/everimus
  - title: twitter
    url: https://twitter.com/everimus_we

# Postal address (add as many lines as necessary)
address:
#  - line: Sample1
#  - line: Sample2

# Build settings
markdown: kramdown
permalink: pretty
